services:
  db:
    image: postgres:15
    environment:
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
        POSTGRES_DB: backend_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "3000:80"
    environment:
      DB_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: development
    volumes:
      - .:/rails
    depends_on:
      - db
    
volumes:
  postgres_data:
