apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cardapio
spec:
  # PROTEÇÃO TESTE 2: Múltiplas Réplicas (Redundância contra Pod Kill)
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          # PROTEÇÃO TESTE 3: Limites de Recursos contra Vizinho Barulhento
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cardapio
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32712
  selector:
    app: frontend
